import { StyleSheet } from "react-native";
import type { Colors } from "../context/ThemeContext";

export const getStyles = (colors: Colors) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },

    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingTop: 52,
      paddingBottom: 16,
    },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: "center",
      alignItems: "center",
    },
    headerTitle: { fontSize: 18, fontWeight: "700", color: colors.text },

    scrollView: { flex: 1 },
    scrollContent: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 20 },

    sectionLabel: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.textMuted,
      marginBottom: 12,
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    sectionRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 24,
      marginBottom: 16,
      gap: 10,
    },
    sectionNumber: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: colors.accent,
      justifyContent: "center",
      alignItems: "center",
    },
    sectionNumberText: { fontSize: 13, fontWeight: "700", color: colors.accent },
    sectionTitle: { fontSize: 16, fontWeight: "700", color: colors.text },

    optionRow: { flexDirection: "row", gap: 12, marginBottom: 4 },
    optionCard: {
      flex: 1,
      minHeight: 116,
      backgroundColor: colors.cardAlt,
      borderRadius: 12,
      padding: 14,
      borderWidth: 1.5,
      borderColor: colors.border,
      justifyContent: "center",
      gap: 6,
    },
    optionCardSelected: {
      borderColor: colors.accent,
      backgroundColor: colors.accentSoft,
    },
    optionTitle: { fontSize: 15, fontWeight: "800", color: colors.text },
    optionSub: { fontSize: 12, color: colors.textMuted, lineHeight: 16 },

    shippingCard: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.cardAlt,
      borderRadius: 12,
      padding: 16,
      borderLeftWidth: 3,
      borderLeftColor: colors.accent,
    },
    shippingInfo: { flex: 1, gap: 2 },
    shippingName: { fontSize: 15, fontWeight: "700", color: colors.text },
    shippingDetail: { fontSize: 13, color: colors.textSecondary },

    checkboxRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 14,
      marginBottom: 8,
      gap: 10,
    },
    checkbox: {
      width: 22,
      height: 22,
      borderRadius: 4,
      borderWidth: 2,
      borderColor: colors.border,
      justifyContent: "center",
      alignItems: "center",
    },
    checkboxChecked: { backgroundColor: "#34C759", borderColor: "#34C759" },
    checkboxLabel: { fontSize: 13, color: colors.textSecondary, flex: 1 },

    inputLabel: {
      fontSize: 12,
      fontWeight: "500",
      color: colors.textMuted,
      marginBottom: 6,
      marginTop: 12,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      color: colors.text,
      backgroundColor: colors.input,
    },
    inputError: {
      borderColor: "#FF3B30",
      borderWidth: 1.5,
      backgroundColor: "#FF3B3010",
    },
    noteInput: {
      minHeight: 92,
      paddingTop: 12,
      lineHeight: 20,
    },

    errorText: {
      fontSize: 11,
      color: "#FF3B30",
      marginTop: 4,
      marginLeft: 4,
      fontWeight: "500",
    },
    errorSummary: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#FF3B3015",
      borderRadius: 10,
      padding: 14,
      marginTop: 20,
      gap: 8,
      borderWidth: 1,
      borderColor: "#FF3B3040",
    },
    errorSummaryText: {
      fontSize: 13,
      color: "#FF3B30",
      fontWeight: "500",
      flex: 1,
    },

    radioRow: { flexDirection: "row", gap: 24, marginTop: 8 },
    radioItem: { flexDirection: "row", alignItems: "center", gap: 8 },
    radio: {
      width: 20,
      height: 20,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: colors.border,
    },
    radioSelected: { borderColor: colors.accent, borderWidth: 5 },
    radioLabel: { fontSize: 14, color: colors.textSecondary },

    cardSection: {
      backgroundColor: colors.cardAlt,
      borderRadius: 14,
      padding: 16,
    },
    cardHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginBottom: 16,
    },
    cardHeaderText: { fontSize: 14, fontWeight: "600", color: colors.text },
    methodRow: { marginBottom: 12 },
    methodTitle: {
      fontSize: 12,
      fontWeight: "500",
      color: colors.textMuted,
      marginBottom: 8,
    },
    methodIcons: { flexDirection: "row", gap: 8 },
    methodChip: {
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    methodChipSelected: {
      borderColor: colors.accent,
      backgroundColor: colors.accentSoft,
    },
    methodChipText: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.textMuted,
    },
    methodChipTextSelected: { color: colors.accent },
    cardRow: { flexDirection: "row", gap: 12 },
    cardRowHalf: { flex: 1 },

    qrisCard: {
      backgroundColor: colors.cardAlt,
      borderRadius: 14,
      padding: 18,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    qrisTitle: { fontSize: 15, fontWeight: "800", color: colors.text },
    qrisBox: {
      width: 240,
      height: 240,
      backgroundColor: "#FFFFFF",
      marginTop: 14,
      marginBottom: 12,
      padding: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: "#E7E7E7",
      alignItems: "center",
      justifyContent: "center",
    },
    qrisImage: { width: "100%", height: "100%" },
    qrisCell: { width: 18, height: 18 },
    qrisCellDark: { backgroundColor: "#111111" },
    qrisCellLight: { backgroundColor: "#FFFFFF" },
    qrisAmount: { fontSize: 18, fontWeight: "800", color: colors.accent },
    uploadBtn: {
      marginTop: 14,
      backgroundColor: "#2D6A4F",
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 16,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
    },
    uploadBtnText: { color: "#FFFFFF", fontSize: 14, fontWeight: "700" },
    proofPreview: {
      width: "100%",
      height: 190,
      borderRadius: 12,
      marginTop: 12,
      backgroundColor: colors.cardAlt,
    },
    mapHint: {
      marginTop: 8,
      fontSize: 12,
      color: colors.textMuted,
      lineHeight: 17,
    },
    distanceCard: {
      marginTop: 10,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: "#2D6A4F14",
      borderWidth: 1,
      borderColor: "#2D6A4F30",
    },
    distanceCardDanger: {
      backgroundColor: "#E5393514",
      borderColor: "#E5393530",
    },
    distanceText: {
      flex: 1,
      fontSize: 13,
      color: "#2D6A4F",
      fontWeight: "700",
    },
    distanceTextDanger: {
      color: "#E53935",
    },

    orderItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
      gap: 12,
    },
    orderImage: { width: 56, height: 56, borderRadius: 8 },
    orderInfo: { flex: 1 },
    orderName: { fontSize: 14, fontWeight: "600", color: colors.text },
    orderQty: { fontSize: 12, color: colors.textMuted, marginTop: 2 },
    orderPrice: { fontSize: 14, fontWeight: "700", color: colors.text },

    summaryCard: {
      backgroundColor: colors.cardAlt,
      borderRadius: 12,
      padding: 16,
      gap: 10,
    },
    summaryRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    summaryLabel: { fontSize: 14, color: colors.textSecondary },
    summaryValue: { fontSize: 14, fontWeight: "600", color: colors.text },
    divider: { height: 1, backgroundColor: colors.border, marginVertical: 6 },
    totalLabel: { fontSize: 16, fontWeight: "700", color: colors.text },
    totalValue: { fontSize: 18, fontWeight: "800", color: colors.accent },
    shippingNote: {
      fontSize: 12,
      color: colors.textMuted,
      lineHeight: 17,
    },
    shippingNoteDanger: {
      color: "#E53935",
      fontWeight: "700",
    },

    bottomBar: {
      backgroundColor: colors.surface,
      borderTopWidth: 1,
      borderTopColor: colors.borderLight,
      paddingHorizontal: 20,
      paddingTop: 14,
      paddingBottom: 34,
    },
    payBtn: {
      backgroundColor: colors.accent,
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: "center",
    },
    payBtnDisabled: { opacity: 0.7 },
    payBtnText: { fontSize: 16, fontWeight: "700", color: "#FFFFFF" },

    modalOverlay: {
      flex: 1,
      backgroundColor: colors.modalOverlay,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 30,
    },
    modalCard: {
      width: "100%",
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 28,
      alignItems: "center",
    },
    modalIcon: { marginBottom: 12 },
    modalTitle: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.textSecondary,
      marginBottom: 4,
    },
    modalAmount: {
      fontSize: 26,
      fontWeight: "800",
      color: colors.text,
      marginBottom: 20,
    },
    modalDivider: {
      width: "100%",
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 16,
    },
    modalRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
      marginBottom: 10,
    },
    modalLabel: { fontSize: 13, color: colors.textMuted },
    modalValue: { fontSize: 13, fontWeight: "600", color: colors.text },
    continueBtn: {
      backgroundColor: "#34C759",
      borderRadius: 14,
      paddingVertical: 14,
      paddingHorizontal: 60,
      marginTop: 20,
      width: "100%",
      alignItems: "center",
    },
    continueBtnText: { fontSize: 16, fontWeight: "700", color: "#FFF" },
  });
