import { StyleSheet } from "react-native";
import { Colors } from "../../context/ThemeContext";

export function createInventoryNfcStyles(colors: Colors) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    content: { padding: 16, paddingBottom: 48 },
    sectionCard: {
      marginTop: 14,
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOpacity: 0.08,
      shadowOffset: { width: 0, height: 3 },
      shadowRadius: 8,
      elevation: 2,
    },
    sectionTitle: { fontSize: 15, fontWeight: "900", color: colors.text },
    sectionSub: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 4,
      lineHeight: 17,
    },
    emptyTags: { marginTop: 14, fontSize: 13, color: colors.textMuted },
    tagList: { marginTop: 12, gap: 8 },
    tagChip: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: 12,
      backgroundColor: colors.surfaceAlt,
    },
    tagChipActive: {
      borderColor: colors.accent,
      backgroundColor: colors.accentSoft,
    },
    tagChipTitle: { fontSize: 14, fontWeight: "800", color: colors.text },
    tagChipTitleActive: { color: colors.accent },
    tagChipUid: { fontSize: 11, color: colors.textSecondary, marginTop: 2 },
    tagChipUidActive: { color: colors.accent },
    tagCard: {
      marginTop: 14,
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOpacity: 0.08,
      shadowOffset: { width: 0, height: 3 },
      shadowRadius: 8,
      elevation: 2,
    },
    tagTopRow: { flexDirection: "row", alignItems: "center", gap: 12 },
    tagIcon: {
      width: 46,
      height: 46,
      borderRadius: 14,
      backgroundColor: colors.accentSoft,
      alignItems: "center",
      justifyContent: "center",
    },
    tagLabel: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: "800",
      textTransform: "uppercase",
    },
    tagValue: {
      fontSize: 15,
      color: colors.text,
      fontWeight: "900",
      marginTop: 2,
    },
    inputLabel: {
      fontSize: 12,
      fontWeight: "800",
      color: colors.textSecondary,
      marginTop: 14,
      marginBottom: 6,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.input,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 14,
      color: colors.text,
    },
    secondaryBtn: {
      marginTop: 10,
      height: 44,
      borderRadius: 12,
      backgroundColor: colors.accentSoft,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
    },
    secondaryBtnText: { color: colors.accent, fontWeight: "800", fontSize: 13 },
    disabledBtn: { opacity: 0.6 },
    addItemBtn: {
      marginTop: 14,
      height: 48,
      borderRadius: 12,
      backgroundColor: colors.accent,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    addItemBtnDisabled: { opacity: 0.45 },
    addItemText: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" },
  });
}
