import { StyleSheet } from "react-native";
import { Colors } from "../../context/ThemeContext";

export function createOverviewStyles(
  colors: Colors,
  isDark: boolean,
  screenWidth: number,
) {
  const tabActiveBg = isDark ? colors.accentSoft : "#E8F5E9";
  const tabActiveText = isDark ? colors.accent : "#1B4332";

  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    loadingWrap: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
    },
    loadingText: { fontSize: 13, color: colors.textMuted, fontWeight: "500" },
    tabBar: {
      flexDirection: "row",
      backgroundColor: colors.card,
      marginHorizontal: 16,
      marginTop: 14,
      borderRadius: 12,
      padding: 4,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOpacity: isDark ? 0.2 : 0.05,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 6,
      elevation: 2,
    },
    tab: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 9,
      borderRadius: 9,
    },
    tabActive: { backgroundColor: tabActiveBg },
    tabText: { fontSize: 13, fontWeight: "600", color: colors.textMuted },
    tabTextActive: { color: tabActiveText },
    content: { padding: 16, paddingBottom: 48 },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
      marginBottom: 12,
      marginTop: 20,
    },
    sectionTitle: { fontSize: 15, fontWeight: "700", color: colors.text },
    statsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
    statCard: {
      width: (screenWidth - 44) / 2,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOpacity: isDark ? 0.15 : 0.04,
      shadowOffset: { width: 0, height: 3 },
      shadowRadius: 8,
      elevation: 2,
    },
    statCardTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 10,
    },
    iconCircle: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    statNum: { fontSize: 26, fontWeight: "800", color: colors.text },
    statLabel: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
      fontWeight: "500",
    },
    chartCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 16,
      paddingBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOpacity: isDark ? 0.15 : 0.04,
      shadowOffset: { width: 0, height: 3 },
      shadowRadius: 8,
      elevation: 2,
    },
    chartHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
    },
    chartLabelSub: {
      fontSize: 11,
      color: colors.textMuted,
      fontWeight: "500",
    },
    chartLabelVal: {
      fontSize: 17,
      fontWeight: "800",
      color: colors.text,
      marginTop: 2,
    },
    periodRow: {
      flexDirection: "row",
      backgroundColor: colors.surfaceAlt,
      borderRadius: 8,
      padding: 2,
      gap: 2,
    },
    periodPill: { paddingHorizontal: 9, paddingVertical: 5, borderRadius: 6 },
    periodPillActive: { backgroundColor: colors.accent },
    periodText: {
      fontSize: 11,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    periodTextActive: { color: "#fff" },
    distCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 16,
      gap: 14,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOpacity: isDark ? 0.15 : 0.04,
      shadowOffset: { width: 0, height: 3 },
      shadowRadius: 8,
      elevation: 2,
    },
    statusRow: { flexDirection: "row", alignItems: "center", gap: 4 },
    statusDot: { width: 7, height: 7, borderRadius: 4, marginRight: 2 },
    statusLabel: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
      width: 60,
    },
    progTrack: {
      flex: 1,
      height: 6,
      backgroundColor: colors.surfaceAlt,
      borderRadius: 4,
      overflow: "hidden",
      marginHorizontal: 8,
    },
    progFill: { height: "100%", borderRadius: 4 },
    statusCount: {
      fontSize: 12,
      fontWeight: "700",
      width: 22,
      textAlign: "right",
    },
    quickActions: { gap: 10 },
    quickBtn: {
      backgroundColor: colors.card,
      borderRadius: 14,
      paddingVertical: 13,
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOpacity: isDark ? 0.12 : 0.04,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 6,
      elevation: 2,
    },
    quickIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    quickLabel: { fontSize: 14, fontWeight: "700", color: colors.text },
    quickDesc: { fontSize: 11, color: colors.textMuted, marginTop: 2 },
    emptyWrap: { alignItems: "center", paddingVertical: 40, gap: 10 },
    emptyText: { fontSize: 14, color: colors.textMuted, fontWeight: "500" },
    orderCard: {
      backgroundColor: colors.card,
      borderRadius: 14,
      marginBottom: 10,
      flexDirection: "row",
      overflow: "hidden",
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOpacity: isDark ? 0.12 : 0.04,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 6,
      elevation: 2,
    },
    orderAccent: { width: 4 },
    orderBody: { flex: 1, padding: 14 },
    orderTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    orderId: { fontSize: 13, fontWeight: "700", color: colors.text },
    orderBottom: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    orderDate: { fontSize: 11, color: colors.textMuted },
    orderPrice: { fontSize: 13, fontWeight: "700", color: colors.accent },
    badge: {
      flexDirection: "row",
      alignItems: "center",
      borderRadius: 20,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    badgeText: { fontSize: 11, fontWeight: "700" },
    lihatSemuaBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      marginTop: 4,
      paddingVertical: 14,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.accent,
    },
    lihatSemuaText: { fontSize: 13, fontWeight: "700", color: colors.accent },
  });
}
